### ISSUE TITLE
用setTimeout做异步吧，否则只能跑在node端

### ISSUE THREAD

**Issue by ManitoYu** [ngtmuzi/np#1]

**Comment by ngtmuzi** [comment]
在node里用`process.nextTick`会比`setTimeout`快不少，有必要的话就参考其他promise库那样根据运行环境来选择函数咯~

**Comment by ManitoYu** [comment]
有没有改为setTimeout跑一遍测试，我之前写了个，有10个测试过不去

**Comment by ngtmuzi** [comment]
之前是用setTimeout跑通的，后来优化的时候发现process.nextTick跑测试用例比它快了差不多4~6S，就改成process.nextTick了
